name: Build and Deploy Library Management System Application server code

on:
  push:
    branches:
      - main
    paths:
      - 'LibMgmtSys.Backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          cd LibMgmtSys.Backend
          docker buildx build -t hanghuynh/backend-image-2:latest -f ./Dockerfile . --load
          echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push hanghuynh/backend-image-2:latest

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            ls
            docker ps -a
            docker pull hanghuynh/backend-image-2:latest
            docker run -d -p 80:80 --name backend-container hanghuynh/backend-image-2:latest
